### PR TITLE
CMake files

### PR DESCRIPTION
**Pull request by Gabrielcarvfer**
Still work-in-progress, but you may want to give it a try. Didn't progress much since didn't manage to make Bellhop work correctly.

Configure ns-3 with `-DNS3_WITH_WOSS_LIBRARY=/path/to/WOSS/`. The WOSS_SOURCE still doesn't build the library.

### CODE REVIEW

**Comment by MetalKnight** [comment]
Hi Grabriel, thanks I'll check it out asap

**Comment by Gabrielcarvfer** [comment]
Needs https://gitlab.com/nsnam/ns-3-dev/-/merge_requests/861, but looks way better :)

**Comment by MetalKnight** [comment]
thanks @Gabrielcarvfer!

**Comment by Gabrielcarvfer** [comment]
Without making changes to the ns3 script, you would need to forward the CMake flags like this
```
CXXFLAGS="-Wno-unused-variable" ./ns3 configure -- -DNS3_WITH_WOSS_SOURCE=path -DNS3_WITH_NETCDF4_INSTALL=path
```
If you were using CMake directly
```
~/ns-3-dev/cmake-cache$ CXXFLAGS="-Wno-unused-variable" cmake -DNS3_WITH_WOSS_SOURCE=path -DNS3_WITH_NETCDF4_INSTALL=path ..
```

**Review by MetalKnight — COMMENTED** [review]
@Gabrielcarvfer  unfortunately the code is NOK.
It is missing many include paths, libraries to be added, and feature defines to be enabled.
let's have a chat over zulip so we can understand how to fix this!
thanks for the effort so far!

Federico

**Comment by Gabrielcarvfer** [comment]
Leaving this gitlab-ci code for reference
<details><summary>gitlab-ci</summary>

```
woss:
  image: ubuntu:21.04 # python 3.9
  only:
    variables:
      - $RELEASE == "weekly"
  before_script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y g++ gfortran m4 autogen autoconf automake libtool cmake ninja-build ccache tar libgsl-dev libgtk-3-dev libboost-dev wget git python3 python3-pip unzip wget
  script:
    - export ORIGIN=$PWD
    - cd ..
    - wget http://telecom.dei.unipd.it/ns/woss/files/at.zip
    - unzip at.zip
    - cd at
    - make install -j15
    - export PATH=$PATH:$PWD/../at/Bellhop:$PWD/../at/Kraken:$PWD/../at/KrakenField:$PWD/../at/Scooter:$PWD/../at/tslib:$PWD/../at/misc
    - cd ..
    - wget http://telecom.dei.unipd.it/ns/woss/files/hdf5-1.8.13.tar.gz
    - tar -zxf hdf5-1.8.13.tar.gz
    - cd hdf5-1.8.13
    - ./configure --enable-shared --prefix=/usr
    - make -j15
    #- make check
    - make install
    - cd ..
    - wget http://telecom.dei.unipd.it/ns/woss/files/netcdf-c-4.7.3.tar.gz
    - tar -zxf netcdf-c-4.7.3.tar.gz
    - cd netcdf-c-4.7.3
    - ./configure --prefix=/usr --enable-netcdf-4 --enable-shared --disable-dap
    - make -j15
    #- make check
    - make install
    - cd ..
    - wget http://telecom.dei.unipd.it/ns/woss/files/netcdf-cxx4-4.3.1.tar.gz
    - tar -zxf netcdf-cxx4-4.3.1.tar.gz
    - cd netcdf-cxx4-4.3.1
    - ./configure --prefix=/usr --enable-shared
    - make -j15
    #- make check
    - make install
    - cd ..
    - wget http://telecom.dei.unipd.it/ns/woss/files/WOSS-v1.12.3.tar.gz
    - tar -zxf WOSS-v1.12.3.tar.gz
    - cd woss-1.12.3
    - ./autogen.sh
    - ./configure --with-pthread --prefix=/usr
    - make -j15
    #- make check
    - make install
    - cd $ORIGIN
    - ./ns3 configure -G Ninja --enable-examples --enable-tests -- -DNS3_WITH_WOSS_SOURCE=$ORIGIN/../woss-1.12.3 # headers are not installed in the prefix
    - ./ns3 run woss-aloha-example
    - ./test.py -s devices-woss
  timeout: 3h
  ```
</details>

**Comment by Gabrielcarvfer** [comment]
I've added both NETCDF and NETCDF4 missing libraries and defines. Regarding the SOURCE/LIBRARY input parameters, I think staying the way it is isn't bad at all. I'm going to make the WIDEN argument the default and remove it. =x

**Comment by MetalKnight** [comment]
superseded by #39

**Pull request closed without merging**
